# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.show-sql=false

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# ================= SENDGRID CONFIG =================
sendgrid.api.key=${SENDGRID_API_KEY}

# ================= EMAIL CONFIG =================
blackint.admin.email=${ADMIN_EMAIL}
blackint.from.email=${FROM_EMAIL}

# ================= SWAGGER (Enable IN PROD) =================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ================= LOGGING =================
logging.level.root=INFO
logging.level.com.blackint=INFO
logging.level.org.springframework.security=ERROR
logging.file.name=blackint-prod.log

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

spring.thymeleaf.cache=true

blackint.frontend.url=https://blackint.in
blackint.assets.url=https://blackint-prod.onrender.com/images