# ================= DATABASE =================
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USER:postgres.wrkwntankrkqjcmwpndu}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT =================
jwt.secret=${JWT_SECRET:localDevSecretKeyForDevelopmentEnvironment01234567}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# ================= SENDGRID CONFIG =================
sendgrid.api.key=${SENDGRID_API_KEY}

# ================= EMAIL CONFIG =================
blackint.admin.email=${ADMIN_EMAIL:contact@blackint.in}
blackint.from.email=${FROM_EMAIL:contact@blackint.in}

# ================= SWAGGER (DEV ONLY) =================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ================= LOGGING =================
logging.level.com.blackint=DEBUG
logging.file.name=blackint-dev.log

blackint.frontend.url=https://blackint-frontend-git-develop-blackints-projects.vercel.app
blackint.assets.url=https://blackint-dev.onrender.com/images
